# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20181024_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot_end_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='slot_time',
        ),
    ]
