# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-25 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20181024_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_date',
            field=models.DateField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_end_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='booking',
            name='slot_time',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
